name: Metrics embed

on:
  schedule: 
    - cron: '0 * * * *'
  push: 
    branches:
      - master
  workflow_dispatch: 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Isometric commit calendar full year
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""
          filename: metrics.plugin.isocalendar.fullyear.svg

      - name: Languages activity - Default algorithm (with details)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          base: ""
          filename: metrics.plugin.languages.details.svg

      - name: Starred topics with icons
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          user: abderahmentrabelsi
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 0
          base: ""
          filename: metrics.plugin.topics.icons.svg

      - name: Lines of code changed - Compact display
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_lines: yes
          plugin_lines_delay: 30
          base: repositories
          filename: metrics.plugin.lines.svg

      - name: Follow-up of issues and pull requests - Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_followup: yes
          plugin_followup_indepth: yes
          base: ""
          filename: metrics.plugin.followup.indepth.svg

      - name: Achievements - Compact display
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          base: ""
          filename: metrics.plugin.achievements.compact.svg

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          base: ""
          filename: metrics.plugin.activity.svg

      - name: Notable contributions - Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          base: ""
          filename: metrics.plugin.notable.indepth.svg

      - name: People - Related to repository
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors
          base: ""
          template: repository
          repo: metrics
          filename: metrics.plugin.people.repository.svg

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: no
          plugin_habits_charts_type: classic
          config_timezone: Europe/Paris
          base: ""
          filename: metrics.plugin.habits.charts.svg

      - name: Repository contributors - By contribution types
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abderahmentrabelsi
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "🧩 Plugins / 🖼️ templates": ["source/plugins/**", "source/templates/**"],
              "📚 Documentation": ["README.md", "**/README.md", "**/metadata.yml"],
              "💻 Code (other)": ["source/**", "Dockerfile"]
            }
          base: ""
          template: repository
          repo: metrics
          filename: metrics.plugin.contributors.categories.svg
